import os
import time
from dotenv import load_dotenv
from google import genai

load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

client = genai.Client(api_key=API_KEY)


class GeminiDocumentGenerator:

    def generate_document(self, document_type, parties, terms, dates):

        prompt = f"""
Create a professional {document_type}.

Parties involved:
{parties}

Terms and Conditions:
{terms}

Effective Date:
{dates}

Create the document with:
1. Title
2. Parties
3. Effective Date
4. Main Clauses
5. Terms and Conditions
6. Signature section

Use clear and formal language.
"""

        for attempt in range(3):

            try:

                response = client.models.generate_content(
                    model="gemini-3.5-flash",
                    contents=prompt
                )

                if response.text:
                    return response.text
                else:
                    return "No document was generated by Gemini."

            except Exception as e:

                if "503" in str(e) or "UNAVAILABLE" in str(e):

                    if attempt == 0:
                        time.sleep(10)

                    elif attempt == 1:
                        time.sleep(20)

                    else:
                        raise

                else:
                    raise